version: 2.1

defaults: &defaults
  working_directory: /home/circleci/project
  resource_class: large
  docker:
    - image: circleci/node:10.16.3
    - image: circleci/postgres:12.0-alpine
      environment:
        POSTGRES_USER: root
        POSTGRES_DB: server_wallet_test
        POSTGRES_PASSWORD: ''

save_dep: &save_dep
  save_cache:
    key: dependency-cache-{{ checksum "yarn.lock" }}
    paths:
      - node_modules
      - packages/*/node_modules

restore_dep: &restore_dep
  restore_cache:
    key: dependency-cache-{{ checksum "yarn.lock" }}

commands:
  log_stats:
    description: 'Log stats '
    parameters:
      file:
        type: string
        default: stats
    steps:
      - run:
          command: bash bin/log_memory.sh <<parameters.file>>
          background: true
  upload_logs:
    description: 'Upload logs '
    parameters:
      file:
        type: string
        default: memory-usage.txt
    steps:
      - store_artifacts:
          path: /home/circleci/<< parameters.file >>.txt
          destination: << parameters.file >>

jobs:
  prepare:
    <<: *defaults
    steps:
      - checkout
      - log_stats:
          file: prepare-stats
      - <<: *restore_dep
      - run: yarn --frozen-lockfile
      - <<: *save_dep

      - persist_to_workspace:
          root: /home/circleci/project
          paths:
            - packages/*/dist
            - packages/*/build
            - packages/*/lib
            - packages/*/node_modules
            - node_modules
      - upload_logs:
          file: prepare-stats

  build:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: /home/circleci/project
      - run: yarn lint:check
      - run: yarn build:ci

  test:
    <<: *defaults
    steps:
      - checkout
      - log_stats:
          file: test-stats
      - attach_workspace:
          at: /home/circleci/project
      - run:
          command: npx lerna run start:ganache --scope=@statechannels/ganache-deployer
          background: true
      # Wait for Ganache to come up and for contract migrations to take place
      - run:
          shell: /bin/sh
          command: |
            wget --retry-connrefused --waitretry=1 --read-timeout=20 --timeout=15 -t 10 http://localhost:3000
      - run: yarn test:ci
      - upload_logs:
          file: test-stats

  # TODO: Get this working
  integration-test:
    <<: *defaults
    steps:
      - checkout:
          path: /home/circleci/project
      - log_stats:
          file: integration-test-stats
      - attach_workspace:
          at: /home/circleci/project
      - run:
          command: (cd packages/wallet && yarn run start)
          background: true
      - run: (cd packages/wallet && yarn run test:ci:integration)
      - upload_logs:
          file: integration-test-stats

workflows:
  statechannels:
    jobs:
      - prepare

      - build:
          requires:
            - prepare

      - test:
          requires:
            - prepare
