version: 2.1

orbs:
  docker: circleci/docker@1.0.1
  slack: circleci/slack@3.4.1

defaults: &defaults
  working_directory: /home/circleci/project
  resource_class: medium
  docker:
    - image: cimg/node:12.18.0
  environment:
    NODE_ENV: test

postgres: &postgres
  <<: *defaults
  docker:
    - image: cimg/node:12.18.0
    - image: circleci/postgres:12-alpine-ram # server-wallet uses a postgresql DB. alpine-ram is a minimal installation that runs in memory (ie. faster tests!)
  environment:
    NODE_ENV: test
    PSQL_ARGS: -p 5432 -h localhost -U postgres
    POSTGRES_USER: postgres

# MACROS

save_dep: &save_dep
  save_cache:
    key: v11-dependency-cache-{{ checksum "yarn.lock" }}
    paths:
      - node_modules
      - packages/client-api-schema/node_modules
      - packages/devtools/node_modules
      - packages/docs-website/node_modules
      - packages/jest-gas-reporter/node_modules
      - packages/nitro-protocol/node_modules
      - packages/server-wallet/node_modules
      - packages/wallet-core/node_modules
      - packages/wire-format/node_modules

restore_dep: &restore_dep
  restore_cache:
    key: v11-dependency-cache-{{ checksum "yarn.lock" }}

# END MACROS

commands:
  log_stats:
    description: 'Log stats '
    parameters:
      file:
        type: string
        default: stats
    steps:
      - run:
          command: bash bin/log_memory.sh <<parameters.file>>
          background: true

  upload_logs:
    description: 'Upload logs '
    parameters:
      file:
        type: string
        default: memory-usage.txt
    steps:
      - store_artifacts:
          path: /home/circleci/<< parameters.file >>.txt
          destination: << parameters.file >>

  upload_gas_report:
    description: 'Upload gas report '
    parameters:
      package:
        type: string
    steps:
      - store_artifacts:
          path: /home/circleci/project/packages/<< parameters.package >>/gas-artifacts

  upload_artifacts:
    description: 'Upload generic artifacts'
    steps:
      - store_artifacts:
          path: /home/circleci/project/artifacts

  notify_slack:
    description: 'Notify slack '
    steps:
      - slack/status:
          failure_message: 'A $CIRCLE_JOB job has failed on $CIRCLE_BRANCH!'
          fail_only: true
          mentions: 'SRHGGRGS0' # Group ID for ActiveDevs
          only_for_branches: 'master,deploy'

  install_postgresql_client:
    description: 'Install postgresql client'
    steps:
      - run:
          command: |
            sudo apt-get update
            sudo apt install -y postgresql-client || true

jobs:
  prepare:
    <<: *defaults
    resource_class: large
    steps:
      - checkout
      - log_stats:
          file: prepare-stats
      - <<: *restore_dep
      - run: yarn --cache-folder ~.cache/yarn
      - run: git diff --exit-code # Fails the job if you forgot to check in tracked installation and/or preparation artifacts (e.g. yarn.lock or api-reports)
      - run: yarn lint:check
      - <<: *save_dep

      - persist_to_workspace:
          root: /home/circleci/project
          paths:
            - packages/*/dist
            - packages/*/build
            - packages/nitro-protocol/artifacts
            - packages/*/lib
            - packages/*/node_modules
            - packages/client-api-schema/types
            - node_modules
      - upload_logs:
          file: prepare-stats
      - notify_slack

  test:
    <<: *postgres
    resource_class: large
    steps:
      - checkout
      - log_stats:
          file: test-stats
      - attach_workspace:
          at: /home/circleci/project
      - install_postgresql_client
      - run:
          name: wallet setup
          working_directory: packages/server-wallet
          command: |
            SERVER_DB_NAME=server_wallet_test yarn db:create $PSQL_ARGS
            SERVER_DB_NAME=server_wallet_test yarn db:migrate
      - run:
          name: test
          command: |
            if [ "${CIRCLE_BRANCH}" = "master" ]
            then
              yarn test:ci
            else
              yarn test:ci:incremental
            fi
          no_output_timeout: 30m
      - upload_logs:
          file: test-stats
      - upload_gas_report:
          package: nitro-protocol
      - notify_slack

  server-wallet-e2e-test:
    <<: *postgres
    steps:
      - checkout
      - attach_workspace:
          at: /home/circleci/project
      - install_postgresql_client
      - run:
          name: server-wallet setup (postgresql migrations)
          working_directory: packages/server-wallet
          command: |
            createdb server_wallet_payer $PSQL_ARGS
            SERVER_DB_NAME=server_wallet_payer yarn db:migrate
            createdb server_wallet_receiver $PSQL_ARGS
            SERVER_DB_NAME=server_wallet_receiver yarn db:migrate
      - run:
          name: server-wallet-e2e-test
          working_directory: packages/server-wallet
          command: yarn test:e2e
          no_output_timeout: 30m
      - upload_artifacts

  server-wallet-stress-test-threaded:
    <<: *postgres
    resource_class: xlarge
    environment:
      NODE_ENV: test
      PSQL_ARGS: -p 5432 -h localhost -U postgres
      SERVER_DB_USER: postgres
      POSTGRES_USER: postgres
      AMOUNT_OF_WORKER_THREADS: 6
      LOG_DESTINATION: /home/circleci/project/artifacts/wallet.log
    steps:
      - checkout
      - attach_workspace:
          at: /home/circleci/project
      - install_postgresql_client
      - run:
          name: server-wallet setup (postgresql migrations)
          working_directory: packages/server-wallet
          command: |
            createdb server_wallet_payer $PSQL_ARGS
            SERVER_DB_NAME=server_wallet_payer yarn db:migrate
            createdb server_wallet_receiver $PSQL_ARGS
            SERVER_DB_NAME=server_wallet_receiver yarn db:migrate
      - run:
          name: server-wallet-stress-test
          working_directory: packages/server-wallet
          command: yarn test:stress
          no_output_timeout: 10m
      - upload_artifacts

  server-wallet-stress-test:
    <<: *postgres
    resource_class: xlarge
    steps:
      - checkout
      - attach_workspace:
          at: /home/circleci/project
      - install_postgresql_client
      - run:
          name: server-wallet setup (postgresql migrations)
          working_directory: packages/server-wallet
          command: |
            createdb server_wallet_payer $PSQL_ARGS
            SERVER_DB_NAME=server_wallet_payer yarn db:migrate
            createdb server_wallet_receiver $PSQL_ARGS
            SERVER_DB_NAME=server_wallet_receiver yarn db:migrate
      - run:
          name: server-wallet-stress-test
          working_directory: packages/server-wallet
          command: yarn test:stress
          no_output_timeout: 10m
      - upload_artifacts

  server-wallet-profiling:
    <<: *postgres
    steps:
      - checkout
      - attach_workspace:
          at: /home/circleci/project
      - install_postgresql_client
      - run:
          name: server-wallet setup (postgresql migrations)
          working_directory: packages/server-wallet
          command: |
            createdb server_wallet_payer $PSQL_ARGS
            SERVER_DB_NAME=server_wallet_payer yarn db:migrate
            createdb server_wallet_receiver $PSQL_ARGS
            SERVER_DB_NAME=server_wallet_receiver yarn db:migrate
      - run:
          name: profile
          working_directory: packages/server-wallet
          command: yarn profile
          no_output_timeout: 10m
      - run:
          command: |
            cp /home/circleci/project/packages/server-wallet/.clinic/*.html  /home/circleci/project/artifacts
      - run:
          command: |
            cp /home/circleci/project/packages/server-wallet/metrics.log  /home/circleci/project/artifacts
      - upload_artifacts

  deploy-docs-website:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: /home/circleci/project
      - when:
          condition:
            equal: [master, << pipeline.git.branch >>]
          steps:
            - run:
                name: build docs-website
                command: yarn lerna run --scope docs-website build
            - run:
                name: deploy docs-website (production)
                command: >
                  npx -p netlify-cli
                  -c 'netlify deploy
                  --site $NITRO_PROTOCOL_NETLIFY_ID
                  --dir=/home/circleci/project/packages/docs-website/build
                  --auth $NETLIFY_ACCESS_TOKEN
                  --message $(git rev-parse --short HEAD)'
                  --prod
      - when:
          condition:
            -not:
              equal: [master, << pipeline.git.branch >>]
          steps:
            - run:
                name: build docs-website
                command: yarn lerna run --scope docs-website --since $(git merge-base $CIRCLE_BRANCH origin/master) build
            - run:
                name: deploy docs-website (preview)
                command: >
                  test -d "/home/circleci/project/packages/docs-website/build" && 
                  npx -p netlify-cli 
                  -c 'netlify deploy 
                  --site $NITRO_PROTOCOL_NETLIFY_ID 
                  --dir=/home/circleci/project/packages/docs-website/build 
                  --auth $NETLIFY_ACCESS_TOKEN 
                  --message $(git rev-parse --short HEAD)'
workflows:
  statechannels:
    jobs:
      - prepare

      - test:
          requires:
            - prepare

      # - server-wallet-profiling:
      #     requires:
      #       - prepare
      - server-wallet-stress-test:
          requires:
            - prepare
      - server-wallet-stress-test-threaded:
          requires:
            - prepare

      - server-wallet-e2e-test:
          requires:
            - prepare
      - deploy-docs-website:
          requires:
            - prepare
