version: 2.1

defaults: &defaults
  working_directory: /home/circleci/project
  resource_class: large
  docker:
    - image: circleci/node:10.16.3

save_code: &save_code
  save_cache:
    key: code-{{ .Revision }}
    paths:
      - .git

save_dep: &save_dep
  save_cache:
    key: dependency-cache-{{ checksum "yarn.lock" }}
    paths:
      - node_modules
      - packages/*/node_modules

restore_code: &restore_code
  restore_cache:
    key: code-{{ .Revision }}

restore_dep: &restore_dep
  restore_cache:
    key: dependency-cache-{{ checksum "yarn.lock" }}

commands:
  log_stats:
    description: "Log stats "
    parameters:
      file:
        type: string
        default: stats
    steps:
      - run:
          command: bash bin/log_memory.sh <<parameters.file>>
          background: true
  upload_logs:
    description: "Upload logs "
    parameters:
      file:
        type: string
        default: memory-usage.txt
    steps:
      - store_artifacts:
          path: /home/circleci/<< parameters.file >>.txt
          destination: << parameters.file >>

jobs:
  build:
    <<: *defaults
    steps:
      - <<: *restore_code
      - checkout
      - log_stats:
          file: build-stats
      - <<: *save_code
      - <<: *restore_dep
      - run:
          name: "yarn --frozen-lockfile"
          command: yarn --frozen-lockfile

      - run: yarn build:ci

      - <<: *save_dep

      - persist_to_workspace:
          root: /home/circleci/project
          paths:
            - packages/*/dist
            - packages/*/build
            - packages/*/lib
            - packages/*/node_modules
            - node_modules
      - upload_logs:
          file: build-stats

  lint:
    <<: *defaults
    steps:
      - <<: *restore_code
      - checkout
      - attach_workspace:
          at: /home/circleci/project
      - run: yarn lint:check

  test:
    <<: *defaults

    steps:
      - <<: *restore_code
      - checkout
      - log_stats:
          file: test-stats
      - attach_workspace:
          at: /home/circleci/project
      - run:
          command: yarn startGanache
          background: true
      - run: yarn test:ci --since $(git merge-base $CIRCLE_BRANCH origin/master)
      - upload_logs:
          file: test-stats

workflows:
  statechannels:
    jobs:
      - build

      - lint:
          requires:
            - build

      - test:
          requires:
            - build
