version: 2.1

defaults: &defaults
  working_directory: /home/circleci/project
  docker:
    - image: counterfactual/statechannels:latest

save_code: &save_code
  save_cache:
    key: code-{{ .Revision }}
    paths:
      - .git

save_dep: &save_dep
  save_cache:
    key: dependency-cache-{{ checksum "yarn.lock" }}
    paths:
      - node_modules

restore_code: &restore_code
  restore_cache:
    key: code-{{ .Revision }}

restore_dep: &restore_dep
  restore_cache:
    key: dependency-cache-{{ checksum "yarn.lock" }}

jobs:
  build:
    <<: *defaults
    steps:
      - <<: *restore_code
      - checkout
      - <<: *save_code

      - <<: *restore_dep
      - run: npm i -g yarn@1.17.3 # because docker image uses 1.13.0
      - run:
          name: "yarn --frozen-lockfile"
          command: yarn --frozen-lockfile

      - run: yarn build:ci

      - <<: *save_dep

      - persist_to_workspace:
          root: /home/circleci/project
          paths:
            - packages/*/dist
            - packages/*/build

  run-tests:
    <<: *defaults
    steps:
      - <<: *restore_code
      - checkout
      - <<: *restore_dep

      - run: sudo npm i -g yarn@1.17.3 # because docker image uses 1.13.0

      - run: yarn --frozen-lockfile # symlink packages' node_modules

      - attach_workspace:
          at: /home/circleci/project

      - run:
          name: Run State Channels tests
          command: yarn test

  run-tslint:
    <<: *defaults
    steps:
      - <<: *restore_code
      - checkout
      - <<: *restore_dep

      - attach_workspace:
          at: /home/circleci/project

      - run: npm i -g yarn@1.17.3 # because docker image uses 1.13.0

      - run: yarn lint

  ensure-updated-lockfiles:
    <<: *defaults
    steps:
      - <<: *restore_code
      - checkout
      - <<: *restore_dep

      - attach_workspace:
          at: /home/circleci/project

      - run: apt-get install -y jq # using this to mutate package.json

      - run: npm i -g yarn@1.17.3 # because docker image uses 1.13.0

      - run:
          name: Check root yarn.lock
          command: yarn --frozen-lockfile

  publish-to-npm:
    <<: *defaults
    steps:
      - <<: *restore_code
      - checkout
      - <<: *restore_dep
      - attach_workspace:
          at: /home/circleci/project
      - run: npm i -g yarn@1.17.3 # because docker image uses 1.13.0
      - run: yarn --frozen-lockfile # symlink packages' node_modules
      - run:
          name: Add NPM_TOKEN auth
          command: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
      - run:
          name: Publish any updated packages to npm
          command: yarn run publish

workflows:
  statechannels:
    jobs:
      - build

      - run-tslint:
          requires:
            - build

      - run-tests:
          requires:
            - build

      - ensure-updated-lockfiles:
          requires:
            - build

      - publish-to-npm:
          requires:
            - build
            - ensure-updated-lockfiles
            - run-tests
            - run-tslint
          filters:
            branches:
              only: master
