version: 2.1
orbs:
  puppeteer: threetreeslight/puppeteer@0.1.2
defaults: &defaults
  working_directory: /home/circleci/project
  resource_class: medium
  docker:
    - image: circleci/node:10.16.3
    - image: circleci/postgres:12.0-alpine
      environment:
        POSTGRES_USER: root
        POSTGRES_DB: hub_wallet_test
        POSTGRES_PASSWORD: ''

save_dep: &save_dep
  save_cache:
    key: dependency-cache-{{ checksum "yarn.lock" }}
    paths:
      - node_modules
      - packages/*/node_modules

restore_dep: &restore_dep
  restore_cache:
    key: dependency-cache-{{ checksum "yarn.lock" }}

commands:
  log_stats:
    description: 'Log stats '
    parameters:
      file:
        type: string
        default: stats
    steps:
      - run:
          command: bash bin/log_memory.sh <<parameters.file>>
          background: true
  upload_logs:
    description: 'Upload logs '
    parameters:
      file:
        type: string
        default: memory-usage.txt
    steps:
      - store_artifacts:
          path: /home/circleci/<< parameters.file >>.txt
          destination: << parameters.file >>

jobs:
  prepare:
    <<: *defaults
    steps:
      - checkout
      - log_stats:
          file: prepare-stats
      - <<: *restore_dep
      - run: yarn --frozen-lockfile
      - <<: *save_dep

      - persist_to_workspace:
          root: /home/circleci/project
          paths:
            - packages/*/dist
            - packages/*/build
            - packages/*/lib
            - packages/*/node_modules
            - packages/client-api-schema/types
            - node_modules
      - upload_logs:
          file: prepare-stats

  build:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: /home/circleci/project
      - run: yarn lint:check
      - run: yarn build:ci

  test:
    <<: *defaults
    steps:
      - checkout
      - log_stats:
          file: test-stats
      - attach_workspace:
          at: /home/circleci/project
      - run:
          command: yarn test:ci
          no_output_timeout: 30m
      - upload_logs:
          file: test-stats

  integration-test:
    <<: *defaults
    steps:
      - checkout:
          path: /home/circleci/project
      - puppeteer/install
      - log_stats:
          file: integration-test-stats
      - attach_workspace:
          at: /home/circleci/project
      - run:
          command: (cd packages/wallet && yarn run start)
          background: true
      - run: (cd packages/wallet && yarn run test:ci:integration)
      - upload_logs:
          file: integration-test-stats

workflows:
  statechannels:
    jobs:
      - prepare

      - build:
          requires:
            - prepare

      - test:
          requires:
            - prepare

      - integration-test:
          requires:
            - prepare
