version: 2.1

orbs:
  docker: circleci/docker@1.0.1
  slack: circleci/slack@3.4.1
  puppeteer: threetreeslight/puppeteer@0.1.2

defaults: &defaults
  environment:
    USE_NATIVE_SOLC: true
  working_directory: /home/circleci/project
  resource_class: medium
  docker:
    - image: counterfactual/statechannels:0.6.9 # Fast contract compilation with solc installed

integration_test_settings: &integration_test_settings
  resource_class: large
  working_directory: /home/circleci/project
  docker:
    - image: circleci/node:10.16.3-browsers
  environment:
    SC_ENV: << parameters.sc_env >>

save_dep: &save_dep
  save_cache:
    key: v4-dependency-cache-{{ checksum "yarn.lock" }}
    paths:
      - node_modules
      - packages/channel-client/node_modules
      - packages/channel-provider/node_modules
      - packages/client-api-schema/node_modules
      - packages/devtools/node_modules
      - packages/e2e-tests/node_modules
      - packages/jest-gas-reporter/node_modules
      - packages/nitro-protocol/node_modules
      - packages/rps/node_modules
      - packages/simple-hub/node_modules
      - packages/tic-tac-toe/node_modules
      - packages/web3torrent/node_modules
      - packages/wire-format/node_modules
      - packages/xstate-wallet/node_modules

restore_dep: &restore_dep
  restore_cache:
    key: v4-dependency-cache-{{ checksum "yarn.lock" }}

save_built_artifacts: &save_built_artifacts
  save_cache:
    # Force a new cache on each build
    key: v3-built-artifacts-cache-{{ epoch }}
    paths:
      # Various TypeScript emissions
      - packages/channel-client/lib
      - packages/channel-provider/lib
      - packages/client-api-schema/lib
      - packages/devtools/lib
      - packages/jest-gas-reporter/lib
      - packages/nitro-protocol/lib
      - packages/simple-hub/lib
      - packages/wire-format/lib
      - packages/xstate-wallet/lib
      # Smart contract compiles
      - packages/nitro-protocol/build
      # Webpack builds & contract compiles
      - packages/rps/build
      - packages/tic-tac-toe/build
      - packages/web3torrent/build
      - packages/xstate-wallet/build

restore_built_artifacts: &restore_built_artifacts
  restore_cache:
    # Restore from the most recently cached version of lib, using a partial key match
    key: v3-built-artifacts-cache-

commands:
  log_stats:
    description: 'Log stats '
    parameters:
      file:
        type: string
        default: stats
    steps:
      - run:
          command: bash bin/log_memory.sh <<parameters.file>>
          background: true

  upload_logs:
    description: 'Upload logs '
    parameters:
      file:
        type: string
        default: memory-usage.txt
    steps:
      - store_artifacts:
          path: /home/circleci/<< parameters.file >>.txt
          destination: << parameters.file >>

  upload_gas_report:
    description: 'Upload gas report '
    parameters:
      package:
        type: string
    steps:
      - store_artifacts:
          path: /home/circleci/project/packages/<< parameters.package >>/gas.json
          destination: << parameters.package >>-gas.json
      - store_artifacts:
          path: /home/circleci/project/packages/<< parameters.package >>/gas.md
          destination: << parameters.package >>-gas.md

  upload_e2e_screenshots:
    description: 'Upload e2e error screengrab '
    steps:
      - store_artifacts:
          path: /home/circleci/project/packages/e2e-tests/screenshots

  upload_e2e_logs:
    description: 'Upload e2e logs'
    steps:
      - store_artifacts:
          path: /home/circleci/project/logs

  notify_slack:
    description: 'Notify slack '
    steps:
      - slack/status:
          failure_message: 'A $CIRCLE_JOB job has failed on $CIRCLE_BRANCH!'
          fail_only: true
          mentions: 'SRHGGRGS0' # Group ID for ActiveDevs
          only_for_branches: 'master,deploy'

  install_xvfb:
    description: 'Install display server' # See https://crbug.com/795759
    steps:
      - run:
          command: sudo apt-get update && sudo apt-get install -yq libgconf-2-4 && sudo apt-get install -y wget xvfb --no-install-recommends

  run_xvfb:
    description: 'Run display server'
    steps:
      - run:
          command: Xvfb -ac :99 -screen 0 1280x800x24 -ac -nolisten tcp -dpi 96 +extension RANDR > /dev/null 2>&1
          background: true

  build_push_release:
    description: 'Build a docker image, push it to the heroku registry, and make a release in heroku'
    parameters:
      dockerfile_path:
        type: string
      pipeline:
        type: string
      app:
        type: string
    steps:
      - run: curl https://cli-assets.heroku.com/install.sh | sh
      - run: heroku container:login
      - docker/build:
          cache_from: registry.heroku.com/<< parameters.app >>/<< parameters.pipeline >>:latest
          dockerfile: << parameters.dockerfile_path >>
          image: registry.heroku.com/<< parameters.app >>/<< parameters.pipeline >>
          tag: latest
      - docker/push:
          image: << parameters.app >>/<< parameters.pipeline >>
          registry: registry.heroku.com
          tag: latest
      - run: heroku container:release -a << parameters.app >> << parameters.pipeline >>

  integration-test:
    description: 'Running integration tests'
    parameters:
      app:
        type: enum
        enum: ['rps', 'web3torrent']
      test_files:
        description: Space-delimited list of test files patterns to run
        type: string
    steps:
      - checkout
      - log_stats:
          file: integration-test-stats
      - attach_workspace:
          at: /home/circleci/project
      - run:
          command: mkdir logs
      - run:
          command: yarn start-servers << parameters.app >>
          background: true
      - run: (cd packages/e2e-tests && yarn test << parameters.test_files >>)
      - upload_logs:
          file: integration-test-stats
      - upload_e2e_logs
      - upload_e2e_screenshots

jobs:
  prepare:
    <<: *defaults
    resource_class: large
    steps:
      - checkout
      - log_stats:
          file: prepare-stats
      - <<: *restore_dep
      - <<: *restore_built_artifacts
      - run: yarn --frozen-lockfile
      - <<: *save_dep
      - <<: *save_built_artifacts

      - persist_to_workspace:
          root: /home/circleci/project
          paths:
            - packages/*/dist
            - packages/*/build
            - packages/*/lib
            - packages/*/node_modules
            - packages/client-api-schema/types
            - node_modules
      - upload_logs:
          file: prepare-stats
      - notify_slack

  build:
    <<: *defaults
    resource_class: large
    steps:
      - checkout
      - log_stats:
          file: build-stats
      - attach_workspace:
          at: /home/circleci/project
      - run: yarn lint:check
      - run:
          name: build
          command: |
            if [ "${CIRCLE_BRANCH}" = "master" ]
            then
                yarn build:ci
            else
                yarn build:ci:incremental
            fi
      - upload_logs:
          file: build-stats
      - notify_slack

  test:
    <<: *defaults
    resource_class: large
    steps:
      - checkout
      - log_stats:
          file: test-stats
      - attach_workspace:
          at: /home/circleci/project
      - run:
          name: test
          command: |
            if [ "${CIRCLE_BRANCH}" = "master" ]
            then
              yarn test:ci
            else
              yarn test:ci:incremental
            fi
          no_output_timeout: 30m
      - upload_logs:
          file: test-stats
      - upload_gas_report:
          package: rps
      - upload_gas_report:
          package: nitro-protocol
      - notify_slack

  integration-test-rps:
    <<: *integration_test_settings
    environment:
      SC_ENV: circle-integration-rps
    steps:
      - integration-test:
          app: rps
          test_files: rps

  integration-test-web3torrent:
    <<: *integration_test_settings
    environment:
      SC_ENV: circle-integration-w3t
    steps:
      - integration-test:
          app: web3torrent
          test_files: web3torrent

  integration-test-web3torrent-with-hub:
    <<: *integration_test_settings
    environment:
      SC_ENV: circle-integration-w3t-with-hub
    steps:
      - integration-test:
          app: web3torrent
          test_files: web3torrent

  integration-test-web3torrent-with-hub-optional:
    <<: *integration_test_settings
    environment:
      SC_ENV: circle-integration-w3t-with-hub
    steps:
      - integration-test:
          app: web3torrent
          test_files: optional

  e2e-test-w3t-production:
    <<: *integration_test_settings
    environment:
      SCREENSHOT_DIR: 'screenshots'
      LOG_DESTINATION: '../../logs'
      SC_ENV: production-goerli
    steps:
      - integration-test:
          app: web3torrent
          test_files: seed-download-complete

  release-pull-request:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: /home/circleci/project
      - run: yarn build:netlify:incremental
      - run: yarn release:netlify:incremental
      - notify_slack

  release-master:
    <<: *defaults
    steps:
      - checkout
      - log_stats:
          file: netlify-stats
      - attach_workspace:
          at: /home/circleci/project
      - run: yarn build:netlify
      - run: yarn release:netlify
      - upload_logs:
          file: netlify-stats
      - notify_slack

  release-netlify-production:
    <<: *defaults
    resource_class: large
    environment:
      SC_ENV: production-goerli
    steps:
      - checkout
      - log_stats:
          file: netlify-stats
      - attach_workspace:
          at: /home/circleci/project
      - run: yarn build:netlify:production
      - run: yarn release:netlify:production
      - upload_logs:
          file: netlify-stats
      - notify_slack

  release-hub-production:
    working_directory: /home/circleci/project
    resource_class: large
    docker:
      - image: circleci/node:10.16
    steps:
      - setup_remote_docker
      - checkout
      - <<: *restore_dep
      - <<: *restore_built_artifacts
      - run:
          rm patches/emberfire+3.0.0-rc.6.patch && cd packages && rm -rf client-api-docs channel-provider
          channel-client client-api-schema e2e-tests persistent-seeder rps tic-tac-toe web3torrent xstate-wallet
      - run: yarn --frozen-lockfile
      - build_push_release:
          dockerfile_path: packages/simple-hub/docker/simple-hub.dockerfile
          pipeline: simple-hub
          app: simple-hub-production
      - slack/status:
          # notify-deployments
          channel: C0125NB072B
          failure_message: ':red_circle: Failed to release simple-hub at $CIRCLE_SHA1!'
          success_message: ':tada: Released simple-hub at $CIRCLE_SHA1 '

  release-persistent-seeder:
    working_directory: /home/circleci/project
    resource_class: large
    docker:
      - image: circleci/node:10.16.3-browsers
    steps:
      - setup_remote_docker
      - checkout
      - <<: *restore_dep
      - <<: *restore_built_artifacts
      - run: rm -rf ./patches && cd ./packages/ && find . -maxdepth 1 ! -path "./channel-provider" ! -path "./client-api-schema" ! -path "./persistent-seeder" ! -path "./e2e-tests" ! -path "./devtools" -exec rm -rf {} ';'
      - build_push_release:
          dockerfile_path: packages/persistent-seeder/persistent-seeder.dockerfile
          pipeline: persistent-seeder
          app: persistent-seeder-production
      - slack/status:
          # notify-deployments
          channel: C0125NB072B
          failure_message: ':red_circle: Failed to release persistent-seeder at $CIRCLE_SHA1!'
          success_message: ':tada: Released persistent-seeder at $CIRCLE_SHA1 '

  push-master-to-deploy:
    working_directory: /home/circleci/project
    resource_class: small
    docker:
      - image: circleci/node:10.16
    steps:
      - checkout
      - run:
          command: |
            git config user.email circle@statechannels.org
            git config user.name Circle
            git checkout deploy
            git rebase origin/master
            git push origin deploy
      - notify_slack

workflows:
  statechannels:
    jobs:
      - prepare

      - build:
          requires:
            - prepare
      - test:
          requires:
            - prepare
      - integration-test-rps:
          requires:
            - prepare
      - integration-test-web3torrent:
          requires:
            - prepare
      - integration-test-web3torrent-with-hub:
          requires:
            - prepare
      - integration-test-web3torrent-with-hub-optional:
          requires:
            - prepare
      - release-pull-request:
          requires:
            - prepare
          filters:
            branches:
              ignore: master
      - release-master:
          requires:
            - prepare
          filters:
            branches:
              only: master
      - release-netlify-production:
          requires:
            - prepare
          filters:
            branches:
              only: deploy

      - release-hub-production:
          filters:
            branches:
              only: deploy

      - release-persistent-seeder:
          filters:
            branches:
              only: deploy

      - e2e-test-w3t-production:
          requires:
            - prepare
            - release-hub-production
            - release-netlify-production
          filters:
            branches:
              only: deploy
  ## We are chosing to disable the daily release for now.
  # scheduled-release:
  #   triggers:
  #     - schedule:
  #         # Run once a day at midnight UTC
  #         cron: '0 0 * * *'
  #         filters:
  #           branches:
  #             only:
  #               - master
  #   jobs:
  #     - push-master-to-deploy
