version: 2.1

defaults: &defaults
  working_directory: /home/circleci/project
  resource_class: large
  docker:
    - image: circleci/node:10.16.3
    - image: circleci/postgres:12.0-alpine-postgis
      environment:
        POSTGRES_USER: root
        POSTGRES_DB: server_wallet_test
        POSTGRES_PASSWORD: ''

save_node_modules: &save_node_modules
  save_cache:
    key: dependency-cache-{{ checksum "yarn.lock" }}
    paths:
      - node_modules
      - packages/*/node_modules

restore_node_modules: &restore_node_modules
  restore_cache:
    key: dependency-cache-{{ checksum "yarn.lock" }}

commands:

  start_memory_logging_process:
    description: 'Start tracking memory usage'
    parameters:
      log_filename:
        type: string
        default: stats
    steps:
      - run:
          command: bash bin/log_memory.sh <<parameters.log_filename>>
          background: true

  upload_memory_usage_artifact:
    description: 'Upload memory usage artifact'
    parameters:
      log_filename:
        type: string
        default: memory-usage.txt
    steps:
      - store_artifacts:
          path: /home/circleci/<< parameters.log_filename >>.txt
          destination: << parameters.log_filename >>

jobs:
  prepare:
    <<: *defaults
    steps:
      - checkout
      - start_memory_logging_process:
          log_filename: prepare-memory-usage.txt
      - <<: *restore_node_modules
      - run: yarn --frozen-lockfile
      - <<: *save_node_modules

      - persist_to_workspace:
          root: /home/circleci/project
          paths:
            - packages/*/dist
            - packages/*/build
            - packages/*/lib
            - packages/*/node_modules
            - node_modules
      - upload_memory_usage_artifact:
          log_filename: prepare-memory-usage.txt

  build:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: /home/circleci/project
      - run: yarn lint:check
      - run: yarn build:ci

  test:
    <<: *defaults
    steps:
      - checkout
      - start_memory_logging_process:
          log_filename: test-memory-usage.txt
      - attach_workspace:
          at: /home/circleci/project
      - run:
          command: npx lerna run start:ganache --scope=@statechannels/ganache-deployer
          background: true
      # Wait for Ganache to come up and for contract migrations to take place
      - run:
          shell: /bin/sh
          command: |
            wget --retry-connrefused --waitretry=1 --read-timeout=20 --timeout=15 -t 10 http://localhost:3000
      - run: yarn test:ci
      - upload_memory_usage_artifact:
          log_filename: test-memory-usage.txt

  # TODO: Get this working
  integration-test:
    <<: *defaults
    steps:
      - checkout:
          path: /home/circleci/project
      - start_memory_logging_process:
          log_filename: integration-test-memory-usage.txt
      - attach_workspace:
          at: /home/circleci/project
      - run:
          command: (cd packages/wallet && yarn run start)
          background: true
      - run: (cd packages/wallet && yarn run test:ci:integration)
      - upload_memory_usage_artifact:
          log_filename: integration-test-memory-usage.txt

workflows:
  statechannels:
    jobs:
      - prepare

      - build:
          requires:
            - prepare

      - test:
          requires:
            - prepare
