version: 2.1

defaults: &defaults
  working_directory: /home/circleci/project
  docker:
    - image: circleci/node:10.16.3

save_code: &save_code
  save_cache:
    key: code-{{ .Revision }}
    paths:
      - .git

save_dep: &save_dep
  save_cache:
    key: dependency-cache-{{ checksum "yarn.lock" }}
    paths:
      - node_modules
      - packages/*/node_modules

restore_code: &restore_code
  restore_cache:
    key: code-{{ .Revision }}

restore_dep: &restore_dep
  restore_cache:
    key: dependency-cache-{{ checksum "yarn.lock" }}

jobs:
  build:
    <<: *defaults
    steps:
      - <<: *restore_code
      - checkout
      - <<: *save_code
      - <<: *restore_dep

      - run:
          name: "yarn --frozen-lockfile"
          command: yarn --frozen-lockfile

      - run: yarn build:ci

      - <<: *save_dep

      - persist_to_workspace:
          root: /home/circleci/project
          paths:
            - packages/*/dist
            - packages/*/build
            - packages/*/lib
            - packages/*/node_modules

  lint:
    <<: *defaults
    steps:
      - <<: *restore_code
      - checkout
      - <<: *restore_dep
      - attach_workspace:
          at: /home/circleci/project
      - run: yarn lint:check

  test:
    <<: *defaults
    steps:
      - <<: *restore_code
      - checkout
      - <<: *restore_dep
      - attach_workspace:
          at: /home/circleci/project
      - run: yarn test:ci --since origin/master

workflows:
  statechannels:
    jobs:
      - build

      - lint:
          requires:
            - build

      - test:
          requires:
            - build
