version: 2.1

defaults: &defaults
  working_directory: /home/circleci/project
  docker:
    - image: circleci/node:10.16.3

save_code: &save_code
  save_cache:
    key: code-{{ .Revision }}
    paths:
      - .git

save_dep: &save_dep
  save_cache:
    key: dependency-cache-{{ checksum "yarn.lock" }}
    paths:
      - node_modules
      - packages/*/node_modules

restore_code: &restore_code
  restore_cache:
    key: code-{{ .Revision }}

restore_dep: &restore_dep
  restore_cache:
    key: dependency-cache-{{ checksum "yarn.lock" }}

commands:
  log_stats:
    description: "Log stats "
    parameters:
      file:
        type: string
        default: stats
    steps:
      - run:
          command: |
            FILE=/home/circleci/<<parameters.file>>.txt
            USAGE=/sys/fs/cgroup/memory/memory.usage_in_bytes
            MAX_USAGE=/sys/fs/cgroup/memory/memory.max_usage_in_bytes
            COUNTER=0
            echo "System $(grep MemTotal /proc/meminfo )" >> $FILE
            while true; do
              echo "${COUNTER} ----------" >> $FILE;
              echo "Current Memory: $(($(cat $USAGE) / 1000000)) mB" >> $FILE
              echo "Max Memory:     $(($(cat $MAX_USAGE) / 1000000)) mB" >> $FILE
              # The %mem field in the output of `ps afu` is incorrect, as it divides by the memory
              # avaiable to the whole system.
              # It seems like containers have about 70 gB of memory, so 1% usage corresponds to ~700 mB.
              # You can validate this assumption on line 1 of $FILE.
              ps afu >> $FILE 
              sleep 1;
              COUNTER=$((COUNTER + 1));
            done 
          background: true
  upload_logs:
    description: "Upload logs "
    parameters:
      file:
        type: string
        default: memory-usage.txt
    steps:
      - store_artifacts:
          path: /home/circleci/<< parameters.file >>.txt
          destination: << parameters.file >>

jobs:
  build:
    <<: *defaults
    steps:
      - <<: *restore_code
      - checkout
      - log_stats:
          file: build-stats
      - <<: *save_code
      - <<: *restore_dep
      - run:
          name: "yarn --frozen-lockfile"
          command: yarn --frozen-lockfile

      - run: yarn build:ci

      - <<: *save_dep

      - persist_to_workspace:
          root: /home/circleci/project
          paths:
            - packages/*/dist
            - packages/*/build
            - packages/*/lib
            - packages/*/node_modules
      - upload_logs:
          file: build-stats

  lint:
    <<: *defaults
    steps:
      - <<: *restore_code
      - checkout
      - <<: *restore_dep
      - attach_workspace:
          at: /home/circleci/project
      - run: yarn lint:check

  test:
    <<: *defaults

    steps:
      - <<: *restore_code
      - checkout
      - log_stats:
          file: test-stats
      - <<: *restore_dep
      - attach_workspace:
          at: /home/circleci/project
      - run: yarn test:ci --since origin/master
      - upload_logs:
          file: test-stats

workflows:
  statechannels:
    jobs:
      - build

      - lint:
          requires:
            - build

      - test:
          requires:
            - build
