version: 2.1

defaults: &defaults
  working_directory: /home/circleci/project
  docker:
    - image: circleci/node:10.16.3

save_code: &save_code
  save_cache:
    key: code-{{ .Revision }}
    paths:
      - .git

save_dep: &save_dep
  save_cache:
    key: dependency-cache-{{ checksum "yarn.lock" }}
    paths:
      - node_modules

restore_code: &restore_code
  restore_cache:
    key: code-{{ .Revision }}

restore_dep: &restore_dep
  restore_cache:
    key: dependency-cache-{{ checksum "yarn.lock" }}

jobs:
  test:
    <<: *defaults
    steps:
      - <<: *restore_code
      - checkout
      - <<: *save_code

      - <<: *restore_dep
      - run:
          name: "yarn --frozen-lockfile"
          command: yarn --frozen-lockfile

      - run: yarn lint
      - run: yarn build:ci
      - run: yarn test --since origin/master

      - <<: *save_dep

      - persist_to_workspace:
          root: /home/circleci/project
          paths:
            - packages/*/dist
            - packages/*/build
            - packages/*/lib

workflows:
  statechannels:
    jobs:
      - test
