# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [master, george/dappeteer3]
  pull_request:
    branches: []

jobs:
  installDependencies:
    name: Install Dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install Dependencies
        uses: bahmutov/npm-install@v1
        env:
          PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: 'true'
        with:
          args: install
      - name: Test Code
        uses: mujo-code/puppeteer-headful@12.3.1
        env:
          CI: 'true'
        with:
          args: cd packages/e2e-tests && yarn test:ci
